# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""


from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAsymRep,
    C2fAsymLite,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    MaxSigmoidAttnBlock,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    TorchVision,    
    BasicStage,
    PatchEmbed_FasterNet,
    PatchMerging_FasterNet,
    Concat_BiFPN,
    FastNormalizedConcat,
    FoldableNormalizedConcat,
    P5SemanticInject,
    SPDConv,
    Partial_conv3,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    GhostConvWide,
    Index,
    LightConv,
    RepConv,
    RepGhostConv,
    AsymRepConv,
    DiverseRepConv,
    ContrastRepConv,
    SpatialAttention,
)
from .head import (
    OBB,
    Classify,
    Detect,
    LRPCHead,
    Pose,
    RepSharedDetect,
    RepSharedPrivateResidualDetect,
    RTDETRDecoder,
    Segment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    v10Detect,

)
from .literature import (
    AdaptiveSparseAIFI,
    C3k2NAM,
    CoordAtt,
    DCNv2,
    ECA,
    ECASpatial,
    EMA,
    FastEMA,
    FrequencyGuidedAttention,
    IncepMix,
    ParallelBackboneBlock,
    WaveletFeatureRefinement,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

__all__ = (
    "AIFI",
    "AdaptiveSparseAIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
    "CBAM",
    "CIB",
    "DFL",
    "DCNv2",
    "ELAN1",
    "EMA",
    "MLP",
    "OBB",
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "A2C2f",
    "AConv",
    "ADown",
    "Attention",
    "BNContrastiveHead",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fAsymRep",
    "C2fAsymLite",
    "C2fAttn",
    "C2fCIB",
    "C2fPSA",
    "C3Ghost",
    "C3k2",
    "C3k2NAM",
    "C3x",
    "CBFuse",
    "CBLinear",
    "ChannelAttention",
    "Classify",
    "Concat",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvTranspose",
    "CoordAtt",
    "DWConv",
    "DWConvTranspose2d",
    "ECA",
    "ECASpatial",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    "Focus",
    "FastEMA",
    "FrequencyGuidedAttention",
    "GhostBottleneck",
    "GhostConv",
    "GhostConvWide",
    "HGBlock",
    "HGStem",
    "ImagePoolingAttn",
    "IncepMix",
    "Index",
    "LRPCHead",
    "LayerNorm2d",
    "LightConv",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "Pose",
    "ParallelBackboneBlock",
    "Proto",
    "RTDETRDecoder",
    "RepC3",
    "RepConv",
    "RepGhostConv",
    "AsymRepConv",
    "DiverseRepConv",
    "ContrastRepConv",
    "RepSharedDetect",
    "RepSharedPrivateResidualDetect",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "Segment",
    "SpatialAttention",
    "TorchVision",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WorldDetect",
    "WaveletFeatureRefinement",
    "YOLOEDetect",
    "YOLOESegment",
    "v10Detect",
    "Concat_BiFPN",
    "FastNormalizedConcat",
    "FoldableNormalizedConcat",
    "P5SemanticInject",
    "Partial_conv3",
)
